language: android
android:
  components:
    - android-27
    - build-tools-27.0.3

before_install:
 - chmod +x gradlew   
    
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug